version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch-lotto-test
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./data:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana-lotto-test
    image: docker.elastic.co/kibana/kibana:8.2.0
    environment:
      - elasticsearch.hosts=http://localhost:9200
    ports:
      - 5601:5601